### ISSUE TITLE
Officers need updating

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg.github.io#19]
The officers section currently contains the names and images of two officers (myself and @EmmaR-OSU) who are no longer officers. Plz update. @JohnSimerlink

**Comment by vipermark7** [comment]
Would it be okay to just remove the pictures + descriptions of the officers or would you have to replace that stuff with something else as well?

**Comment by J3RN** [comment]
@vipermark7 I'm not terribly opposed to eliminating the section altogether. My only concern would be potential sponsors looking for a contact and being unable to find one.

**Comment by vipermark7** [comment]
Well, I was actually just asking about removing only your and Emma's pictures and not all the officers' pictures. Maybe we could have a tab or other element that just says "Sponsor Us?" and displays info about officers or other relevant people

**Comment by J3RN** [comment]
Oh, I see. Well, I was thinking that the images and names of Emma and me should be updated with the images and names of the current president and treasurer.

Alright, better idea. I was looking at the ACM-W site for inspiration, and they have a [simple "Contact Us" page](https://acmw.org.ohio-state.edu/contact). I'd be down for something like that, maybe with just the president's name and a link to email the club email.

**Comment by vipermark7** [comment]
Well I guess it's time to figure out how to code a "Contact/Sponsor Us" page! >:D

**Comment by vipermark7** [comment]
this will take a while D:

**Comment by vipermark7** [comment]
Could we discuss this on IRC? Also is there a way to post images directly into IRC or would I have to do that via links to Imgur or something?

**Comment by J3RN** [comment]
@vipermark7 We can discuss in IRC or [Gitter](https://gitter.im/CWDG/). Gitter natively supports images, IRC doesn't (but some clients might throw images out to S3, pretending to have native image support).

**Comment by vipermark7** [comment]
Oh. Ya I just joined Gitter so I will try to draw a rough sketch of what I have in mind for that contact page

**Comment by J3RN** [comment]
I believe all that's missing (unless you're unhappy with the pictures, @JohnSimerlink), is to run `rake publish`

**Comment by vipermark7** [comment]
rekt
