### ISSUE TITLE
Autumn 2016 Schedule

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg.github.io#21]
The site right now shows this:
<img width="406" alt="screen shot 2016-08-28 at 1 06 55 pm" src="https://cloud.githubusercontent.com/assets/2058614/18035256/764398e2-6d20-11e6-962d-dd8ec9e638c6.png">

And the "Meetings" tab has this:
<img width="1022" alt="screen shot 2016-08-28 at 1 07 02 pm" src="https://cloud.githubusercontent.com/assets/2058614/18035257/8626d31e-6d20-11e6-8969-99d8431e194b.png">

It might be worthwhile to add some JavaScript that hides the older meetings, instead of just deleting them from the file. I guess that's a separate issue.

**Comment by vipermark7** [comment]
I'm interested. @JohnSimerlink is briefing me a little bit on what to expect.

**Comment by vipermark7** [comment]
First I will need to know what meetings are coming up next/

**Comment by JohnSimerlink** [comment]
@vipermark7 , an up to date list of our meetings is located here: https://calendar.google.com/calendar/embed?src=cwdgosu%40gmail.com&ctz=America/New_York

**Comment by vipermark7** [comment]
I tried working on this stuff for a while, but making changes to the Ruby app isn't working as detailed in the README

**Comment by J3RN** [comment]
@vipermark7 Could you tell me what exactly is not working from the instructions in the README?

**Comment by vipermark7** [comment]
Sorry, will have to get back to you on that. Haven't tried to build the app in a while, unfortunately.

**Comment by vipermark7** [comment]
Fixed. Added new dates until November 1st. 

obligatory rekt :)
