### ISSUE TITLE
Make publishing simpler

### ISSUE THREAD

**Issue by moore3071** [CWDG/cwdg.github.io#30]
Publishing is currently difficult due to good old Ruby dependency problems. I see a few options:

- update the Gemfile.lock to be compatible with Ruby 2.4 (the current Ruby release)
  1. make sure you have ruby 2.4 (ruby --version)
  2. remove the previous gemfile.lock
  3. run bundle install
  4. add the new gemfile.lock to the repo
- (**Not recommended**) remove the Gemfile.lock from the repository and rely on users ensuring that everything builds correctly before publishing.
- Have Travis CI publish upon changes to the source branch. This will be a slight pain in the butt to set up as GH doesn't have organization tokens as far as I know, so someone we'll need to give Travis encrypted credentials to push to master.

I'd recommend the first option for now.

**Comment by vipermark7** [comment]
Will work on this in tomorrow's meeting, don't forget to remind me! :D

**Comment by vipermark7** [comment]
Based on what we did this Tuesday could we mark this issue closed?

**Comment by moore3071** [comment]
Sure, although I'll open an issue to put on the backburner for deploying via Travis as mentioned in bullet point 3 of this issue.
